name: CI

on:
  push:
    branches:
      - main
      

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
     - name: Setup Python
       uses: actions/setup-python@v5.1.1
       with:
         python-version: '3.12.1'


     - name: Install dependencies
       run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

     - run: python cosinesimilarity2.py
